apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
  namespace: market
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: 2admi/otus-market-saga-delivery:1.0.0
          ports:
            - containerPort: 8880
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: DB_HOST
              value: "postgres-delivery"
            - name: DB_PORT
              value: "5435"
            - name: DB_NAME
              value: "delivery_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
