apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: market
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8883
  type: ClusterIP