apiVersion: v1
kind: Service
metadata:
  name: postgres-billing
  namespace: market
spec:
  ports:
    - port: 5433
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-billing
  type: ClusterIP
