apiVersion: v1
kind: Service
metadata:
  name: postgres-delivery
  namespace: market
spec:
  ports:
    - port: 5435
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-delivery
  type: ClusterIP
