apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: market
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-order
  type: ClusterIP
