apiVersion: v1
kind: Service
metadata:
  name: postgres-warehouse
  namespace: market
spec:
  ports:
    - port: 5434
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-warehouse
  type: ClusterIP
