apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-deployment
  namespace: market
  labels:
    app: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: 2admi/otus-market-saga-billing:1.1.0
          ports:
            - containerPort: 8881
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: DB_HOST
              value: "postgres-billing"
            - name: DB_PORT
              value: "5433"
            - name: DB_NAME
              value: "billing_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
