apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: market
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 2admi/otus-market-saga-order:1.1.1
          ports:
            - containerPort: 8880
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: DB_HOST
              value: "postgres-order"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "order_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
